import math
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

tau = 39
eta = 2
beta = tau * eta
gamma1 = 2**17

def get_dist_x(mean):
    x = np.arange(-beta, beta + 1)
    return norm.pdf(x, loc=mean, scale=math.sqrt((tau * eta * (eta + 1)) / 3))

def get_dist_z():
    x = np.arange(-beta, beta + 1)
    sigma = math.sqrt((tau * eta * (eta + 1)) / 3)

    # 離散化した正規分布
    dist_x = norm.pdf(x, loc=0, scale=sigma)
    dist_x = dist_x / dist_x.sum()

    # 区間上の一様分布
    rect = np.ones(2 * gamma1)
    rect = rect / rect.sum()

    # 畳み込み
    z = np.convolve(rect, dist_x, mode="full")
    return z;

def main():
    x = np.arange(-beta, beta + 1)
    dist_x = norm.pdf(x, loc=0, scale=math.sqrt((tau * eta * (eta + 1)) / 3))
    z = np.zeros(2 * gamma1 + 2 * beta)

    for i in range(2 * gamma1):
        z[i:i + 2 * beta + 1] += dist_x

    plt.plot(z[-2*beta:-60])
    plt.savefig("dist.png")

### Below code is generated by ChatGPT
def chappy():
    z = get_dist_z()

    plt.plot(z[-2*beta:-1])
    plt.savefig("dist.png")

if __name__ == "__main__":
    chappy()





